version: "3.8"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=snippetbox
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "33061:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
